name: flutterjdshop

description: 仿京东商城app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #flutter_swiper插件
  flutter_swiper_null_safety: ^1.0.2
  #带缓存功能的网络图片插件
  cached_network_image: ^3.2.0
  #flutter_screenutil屏幕适配插件
  flutter_screenutil: ^5.5.3
  #http请求库
  dio: ^5.8.0+1
  #状态管理
  provider: ^6.0.0
  #toast
  fluttertoast: ^8.0.9
  #本地配置文件
  shared_preferences: ^2.0.15
  #国际化
  flutter_localizations:
    sdk: flutter
  intl: any
  #md5加密
  crypto: ^3.0.2
  #省市区选择器
  city_pickers: ^1.0.1
  #支付宝支付插件
  tobias: ^5.1.2
  #webview
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # 开启国际化代码自动生成（关键）
  generate: true
  uses-material-design: true
  assets:
    - images/

flutter_intl:
  enabled: true